### PR TITLE
added Blob support

### PR DESCRIPTION
**Pull request by stevenxxiu**
I didn't add a test case because node doesn't have Blob. I tried it on chrome and it seems to work with blobs and files.

### CODE REVIEW

**Comment by dumbmatter** [comment]
Thanks! One question, would `input.slice()` make more sense than `new Blob([input])`, like [this](http://stackoverflow.com/questions/37802025/how-to-clone-a-blob-in-javascript)? Probably they do the same thing, I guess?

**Comment by dumbmatter** [comment]
And one more question... both of these ways will lose blob.type unless it's manually specified, like `input.slice(0, input.length, input.type)` or `new Blob([input], {type: input.type})`. Does that make sense to include?

**Comment by stevenxxiu** [comment]
Thanks for the feedback! How about `input.slice(0, input.size, input.type);` ? I think that covers the `type` case.

**Comment by dumbmatter** [comment]
Thanks :)

**Pull request merged**
